### ISSUE TITLE
ble dependency in this module - requirement which might need a split?

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-hal-nrf51822-mcu#27]
Is this module https://github.com/ARMmbed/ble-nrf51822 really needed for this module? This mbed hal does not need ble implementation, therefore latest changes in BLE should not affect this module, should it?
What is needed in this module from ble-nrf51822 ?

**Comment by rgrover** [comment]
I looked into this too. It turns out that the implementation of critical section and some other high level HAL primitives needs APIs from the Nordic SDK. These currently all reside in ble-nrf51822. Ideally, HAL related softdevice APIs should be contained in mbed-hal-nrf51822-mcu (or something similar); not in ble-nrf51822. But then it splitting the Nordic SDK into ble-nrf51822 and mbed-hal* becomes a maintenance overhead because we'll need to always take the extra step of updating mbed-hal-nrf* when we pull in a new nRF SDK.

I think we should separate out the nRF SDK files from ble-nrf51822 and make it into a separate yotta module. Then both ble-nrf51822 and mbed-hal-* can depend on that. Then the version change for BLE api would only affect ble-nrf51822 but not mbed-hal-nrf*.

We have already identified this improvement as IOTSFW-1179

**Comment by 0xc0170** [comment]
> I think we should separate out the nRF SDK files from ble-nrf51822 and make it into a separate yotta module. Then both ble-nrf51822 and mbed-hal-* can depend on that. Then the version change for BLE api would only affect ble-nrf51822 but not mbed-hal-nrf*.

That's what I was asking if it's possible, thus mbed-hal would only depend on "nordic target files".  Thanks for an answer, keep us updated

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1197

**Comment by LiyouZhou** [comment]
@0xc0170 The split of nordic file has happened. Depends only on "nrf51-sdk": "^1.0.0" now.

**Comment by 0xc0170** [comment]
@LiyouZhou Can you reference the PR/commit here? To check if it was fixed. We can then close the issue

**Comment by 0xc0170** [comment]
Found it, https://github.com/ARMmbed/mbed-hal-nrf51822-mcu/pull/33
